local projects = {
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\04_BalancedSizzle_FoliageCanopy_FoliageYielding_C1_极轻细雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\13_ForestWhisper_FoliageDense_FoliageYielding_C3_小阵雨_中距.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\01_AiryBreeze_FoliageDense_WoodRoof_C5_中雨极湿_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\13_ForestWhisper_FoliageCanopy_WoodRoof_C7_中雨密集_干燥_远方.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\10_EchoRiver_FoliageDense_WoodRoof_C2_极轻密集_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\01_AiryBreeze_FoliageCanopy_WoodRoof_C9_大雨_远方.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\19_ThickShower_FoliageDense_Concrete_C7_中雨密集_干燥_远方.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\16_SlowWaterfall_FoliageDense_Water_C1_极轻细雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\15_ImmersiveFuzz_FoliageCanopy_Water_C3_小阵雨_中距.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\12_FlowingRumble_FoliageDense_StoneEchoing_C3_小阵雨_中距.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\14_GentleSwish_FoliageDense_FoliageLush_C9_大雨_远方.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\12_FlowingRumble_FoliageCanopy_WoodRoof_C4_中雨_均衡.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\04_BalancedSizzle_FoliageCanopy_FoliageLush_C9_大雨_远方.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\16_SlowWaterfall_FoliageCanopy_FoliageLush_C9_大雨_远方.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\20_WarmBuzz_FoliageCanopy_StoneEchoing_C3_小阵雨_中距.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\15_ImmersiveFuzz_FoliageCanopy_FoliageYielding_C1_极轻细雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\03_BalancedFlow_FoliageCanopy_FoliageLush_C1_极轻细雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\05_BreezyHiss_FoliageDense_Concrete_C8_大雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\05_BreezyHiss_FoliageCanopy_Water_C1_极轻细雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\16_SlowWaterfall_FoliageCanopy_FoliageYielding_C5_中雨极湿_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\01_AiryBreeze_FoliageCanopy_WoodRoof_C8_大雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\17_SpookyWhisper_FoliageDense_Concrete_C3_小阵雨_中距.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\05_BreezyHiss_FoliageCanopy_WoodRoof_C4_中雨_均衡.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\15_ImmersiveFuzz_FoliageCanopy_FoliageYielding_C4_中雨_均衡.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\14_GentleSwish_FoliageCanopy_WoodRoof_C2_极轻密集_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\15_ImmersiveFuzz_FoliageDense_WoodRoof_C8_大雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\02_AiryFlow_FoliageCanopy_Water_C1_极轻细雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\03_BalancedFlow_FoliageDense_StoneEchoing_C1_极轻细雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\14_GentleSwish_FoliageDense_FoliageYielding_C1_极轻细雨_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\04_BalancedSizzle_FoliageCanopy_Concrete_C9_大雨_远方.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\20_WarmBuzz_FoliageDense_FoliageYielding_C5_中雨极湿_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\11_ExpansiveShower_FoliageCanopy_FoliageLush_C4_中雨_均衡.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\05_BreezyHiss_FoliageCanopy_FoliageYielding_C4_中雨_均衡.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\05_BreezyHiss_FoliageDense_FoliageLush_C2_极轻密集_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\08_DenseStream_FoliageDense_StoneEchoing_C4_中雨_均衡.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\17_SpookyWhisper_FoliageCanopy_Concrete_C3_小阵雨_中距.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\08_DenseStream_FoliageCanopy_StoneEchoing_C5_中雨极湿_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\19_ThickShower_FoliageCanopy_StoneEchoing_C2_极轻密集_近贴.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\01_AiryBreeze_FoliageDense_FoliageYielding_C4_中雨_均衡.rpp",
  "\\\\wsl.localhost\\Ubuntu\\home\\leo\\workspace\\relaxASMR\\design\\vst\\render_jobs\\18_StrongHiss_FoliageCanopy_Concrete_C5_中雨极湿_近贴.rpp",
}

for i, path in ipairs(projects) do
  reaper.Main_openProject(path)
  reaper.Main_OnCommand(42230, 0) -- Render
end
reaper.Main_OnCommand(40004, 0) -- Quit REAPER
